package com.brassappmanager.persistence.entities;

// Generated Jun 20, 2015 11:05:54 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "currency", schema = "public")
@SequenceGenerator(name = "currency_seq", sequenceName = "currency_id_seq")
public class Currency implements java.io.Serializable {

	private long id;
	private String currencyName;
	private Set<Book> books = new HashSet<>(0);
	private Set<Payment> payments = new HashSet<>(0);
	private Set<Instrument> instruments = new HashSet<>(0);

	public Currency() {
	}

	public Currency(String currencyName) {
		this.currencyName = currencyName;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "currency_seq")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "currency_name", length = 45)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}
	
	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
		
	}

}
