package com.brassappmanager.persistence.entities;

// Generated Jun 20, 2015 11:05:54 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * InstrumentType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "instrument_type", schema = "public")
@SequenceGenerator(name = "instrument_type_seq", sequenceName = "instrument_type_id_seq")
public class InstrumentType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<Instrument> instruments = new HashSet<Instrument>(0);

	public InstrumentType() {
	}

	public InstrumentType(String type, Set<Instrument> instruments) {
		this.type = type;
		this.instruments = instruments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "instrument_type_seq")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrumentType")
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}

	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
	}

}
