package com.brassappmanager.persistence.entities;

// Generated Jun 20, 2015 11:05:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "person", schema = "public")
@SequenceGenerator(name = "person_seq", sequenceName = "person_id_seq")
public class Person implements java.io.Serializable {

	private long id;
	private String firstName;
	private String lastName;
	private String address;
	private Date birthDate;
	private String yearOfStudy;
	private Date subscription;
	private Set<Department> departments = new HashSet<>(0);
	private Set<Book> books = new HashSet<>(0);
	private Set<Instrument> instruments = new HashSet<>(0);

	public Person() {
	}

	public Person(String firstName, String lastName, String address,
			Date birthDate, String yearOfStudy, Date subscription) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.birthDate = birthDate;
		this.yearOfStudy = yearOfStudy;
		this.subscription = subscription;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "person_seq")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", length = 13)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "year_of_study", length = 20)
	public String getYearOfStudy() {
		return this.yearOfStudy;
	}

	public void setYearOfStudy(String yearOfStudy) {
		this.yearOfStudy = yearOfStudy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscription", length = 13)
	public Date getSubscription() {
		return this.subscription;
	}

	public void setSubscription(Date subscription) {
		this.subscription = subscription;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "person_department", schema = "public", joinColumns = { @JoinColumn(name = "person_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "department_id", nullable = false, updatable = false) })
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "person_book", schema = "public", joinColumns = { @JoinColumn(name = "person_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "book_id", nullable = false, updatable = false) })
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "person_instrument", schema = "public", joinColumns = { @JoinColumn(name = "person_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "instrument_id", nullable = false, updatable = false) })
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}

	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
	}

}
